<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aefbe4e8-95b3-4c36-8093-5d2021abf1e8</elementGuidId>
    <imagePath></imagePath>
    <name>link_placeOrder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}cart') and equals(@text,'Place an order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Place an order\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}cart</value>
        <webElementGuid>ad3ffcb7-e18d-43b6-bf71-a365e0262321</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place an order</value>
        <webElementGuid>ad3ffcb7-e18d-43b6-bf71-a365e0262321</webElementGuid>
    </webElementProperties>
</WebElementEntity>